services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./client:/app/client
      - ./shared:/app/shared
      - ./vite.client.config.js:/app/vite.client.config.js
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./postcss.config.js:/app/postcss.config.js
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - VITE_API_URL=https://api.housecraft.snaart.com
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.housecraft.rule=Host(`housecraft.snaart.com`)"
      - "traefik.http.routers.housecraft.entrypoints=websecure"
      - "traefik.http.routers.housecraft.tls.certresolver=myresolver"
      - "traefik.http.routers.housecraft.priority=10"
      - "traefik.http.services.housecraft.loadbalancer.server.port=3000"
    networks:
      - traefik_network
    expose:
      - "80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.housecraftapi.rule=Host(`api.housecraft.snaart.com`)"
      - "traefik.http.routers.housecraftapi.entrypoints=websecure"
      - "traefik.http.routers.housecraftapi.tls.certresolver=myresolver"
      - "traefik.http.routers.housecraftapi.priority=10"
      - "traefik.http.services.housecraftapi.loadbalancer.server.port=80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/houseapp
      - SECRET_KEY=your-secret-key-here

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=houseapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traefik_network

volumes:
  postgres_data:

networks:
  traefik_network:
    external: true
